apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  creationTimestamp: null
  name: plans.upgrade.example.com
spec:
  group: upgrade.example.com
  names:
    kind: Plan
    listKind: PlanList
    plural: plans
    singular: plan
  scope: Namespaced
  versions:
  - name: v1alpha1
    schema:
      openAPIV3Schema:
        description: Plan is the Schema for the plans API
        properties:
          apiVersion:
            description: 'APIVersion defines the versioned schema of this representation
              of an object. Servers should convert recognized schemas to the latest
              internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources'
            type: string
          kind:
            description: 'Kind is a string value representing the REST resource this
              object represents. Servers may infer this from the endpoint the client
              submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds'
            type: string
          metadata:
            type: object
          spec:
            description: Spec defines the desired state of Plan resource
            properties:
              aap:
                description: Configuration for Ansible Automation Platform
                properties:
                  controller_host:
                    description: Server address of AAP (without protocol)
                    pattern: ^.+$
                    type: string
                  controller_oauthtoken:
                    description: OAuthToken generated with {{controller_host}}/api/v2/tokens/
                    pattern: ^.+$
                    type: string
                  job_template:
                    description: Name of the job template being launched
                    pattern: ^.+$
                    type: string
                required:
                - controller_host
                - controller_oauthtoken
                - job_template
                type: object
            type: object
          status:
            description: Status defines the observed state of Plan resource
            type: object
            x-kubernetes-preserve-unknown-fields: true
        required:
        - spec
        type: object
    served: true
    storage: true
    subresources:
      status: {}
status:
  acceptedNames:
    kind: ""
    plural: ""
  conditions: null
  storedVersions: null
