# permissions for end users to view plans.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: plan-viewer-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: ansible-test
    app.kubernetes.io/part-of: ansible-test
    app.kubernetes.io/managed-by: kustomize
  name: plan-viewer-role
rules:
- apiGroups:
  - upgrade.example.com
  resources:
  - plans
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - upgrade.example.com
  resources:
  - plans/status
  verbs:
  - get
