---
# Set Control Plane and Work Plane Nodes
- name: Set Node Facts
  ansible.builtin.set_fact:
    cp_nodes: "{{ nodes | community.general.json_query(cp_query) }}"
    wp_nodes: "{{ nodes | community.general.json_query(wp_query) }}"
  vars:
    cp_query: resources[?(metadata.labels."node-role.kubernetes.io/master"=='')]
    wp_query: resources[?(metadata.labels."node-role.kubernetes.io/worker"=='')]

# Gather Machine Config Pools
- name: Gather Control Plane Machine Config Pools
  kubernetes.core.k8s_info:
    api_version: "machineconfiguration.openshift.io/v1"
    kind: MachineConfigPool
  register: machineconfigpools

# Set Control Plane Pool and Work Plane Pools
- name: Set MCP Facts
  ansible.builtin.set_fact:
    cp_mcp_names: "{{ machineconfigpools | community.general.json_query(cp_query) }}"
    wp_mcp_names: "{{ machineconfigpools | community.general.json_query(wp_query) }}"
  vars:
    cp_query: resources[?(metadata.labels."pools.operator.machineconfiguration.openshift.io/master"=='')].metadata.name
    wp_query: resources[?!(metadata.labels."pools.operator.machineconfiguration.openshift.io/master"=='' || metadata.labels."pools.operator.machineconfiguration.openshift.io/canary"=='')].metadata.name

# Pause Worker Pools
- name: Worker Pool Modifcation Block
  block:
    # Pause Worker Pools
    - name: Pause Worker Pools
      kubernetes.core.k8s:
        state: patched
        template: workermachineconfigpool.yml
        wait: true
      vars:
        workerpools: "{{ wp_mcp_names }}"

    # Upon Success, Set Paused Status true
    - name: Report Paused
      operator_sdk.util.k8s_status:
        api_version: "upgrade.example.com/v1alpha1"
        kind: Plan
        name: "{{ ansible_operator_meta.name }}"
        namespace: "{{ ansible_operator_meta.namespace }}"
        status:
          workermachineconfigpools:
            paused: true

  rescue:
    # Upon Failure, Set Paused Status false
    - name: Report Not Paused
      operator_sdk.util.k8s_status:
        api_version: "upgrade.example.com/v1alpha1"
        kind: Plan
        name: "{{ ansible_operator_meta.name }}"
        namespace: "{{ ansible_operator_meta.namespace }}"
        status:
          workermachineconfigpools:
            paused: false

  always:
    # Update Control Flow Variable
    - name: Set Machine Config Pools Paused
      ansible.builtin.set_fact:
        machine_config_pools_paused: "{{ (ansible_failed_result is not defined) | ternary('true', 'false') }}"
