---
# Launch an AAP job, passing in the node name for variable host information
- name: Job Execution Block
  block:
    # Launch the Job
    - name: Launch
      awx.awx.job_launch:
        controller_host: "{{ vars.aap.controller_host }}"
        controller_oauthtoken: "{{ vars.aap.controller_oauthtoken }}"
        job_template: "{{ vars.aap.job_template }}"
        extra_vars:
          variable_host: "{{ item.metadata.name }}"
        wait: true
      register: launch_results

    # Upon Success, Update Status
    - name: Report Job Run Success
      operator_sdk.util.k8s_status:
        api_version: "upgrade.example.com/v1alpha1"
        kind: Plan
        name: "{{ ansible_operator_meta.name }}"
        namespace: "{{ ansible_operator_meta.namespace }}"
        status:
          jobs:
            status: "complete"

    # Upon Success, Label the Node with the Canary MCP Label
    - name: Add Mutable Label
      kubernetes.core.k8s_json_patch:
        kind: Node
        api_version: "v1"
        name: "{{ item.metadata.name }}"
        patch:
          - op: add
            path: "/metadata/labels/upgrades.example.com~1mutable"
            value: ''

    # Wait For Upgrade To Complete
    - name: Wait Until Node Version Matches Desired Version
      kubernetes.core.k8s_info:
        api_version: "v1"
        kind: Node
        name: "{{ item.metadata.name }}"
      register: actual_version
      until: desired_version == actual_version.resources[0].metadata.labels['machineconfiguration.openshift.io/release-image-version']

  rescue:
    # Upon Failure, Update Status
    - name: Report Job Run Failure
      operator_sdk.util.k8s_status:
        api_version: "upgrade.example.com/v1alpha1"
        kind: Plan
        name: "{{ ansible_operator_meta.name }}"
        namespace: "{{ ansible_operator_meta.namespace }}"
        status:
          job:
            status: "job incomplete"

  always:
    # Update Control Flow Variable
    - name: Set Worker Nodes Upgraded
      ansible.builtin.set_fact:
        worker_nodes_upgraded: "{{ (ansible_failed_result is not defined) | ternary('true', 'false') }}"
