---
- name: Create/Delete Canary Machine Config Pool
  kubernetes.core.k8s:
    state: "{{ state | default('present') }}"
    template: canarymachineconfigpool.yml
  vars:
    resource_name: "{{ _upgrade_example_com_plan.metadata.name }}"
    resource_namespace: "{{ _upgrade_example_com_plan.metadata.namespace }}"
    resource_kind: "{{ _upgrade_example_com_plan.kind }}"
    resource_group: "{{ _upgrade_example_com_plan.apiVersion | split('/') | first }}"