---
# Is there an update?
- name: Identify Update Status
  ansible.builtin.import_tasks: upgrade.yml

# Is the control plane finished?
#- name: Pause Nodes
#  ansible.builtin.import_tasks: machineconfigpool.yml

# Is there a canary pool?
- name: Create Canary Pool
  ansible.builtin.import_tasks: canary.yml

- name: Run Job
  ansible.builtin.import_tasks: jobs.yml