---
# Is the CRD valid?
- name: Validate CRD
  ansible.builtin.include_tasks: set_validation_status.yml

# Is there an update?
- name: Identify Update Status
  ansible.builtin.include_tasks: set_upgrade_status.yml

# Is the control plane finished?
- name: Pause Nodes
  ansible.builtin.include_tasks: modify_mcps.yml

# Is there a canary pool?
- name: Create Canary Pool
  ansible.builtin.include_tasks: modify_canary_mcp.yml

# Run Jobs
- name: Run Job
  ansible.builtin.include_tasks: run_jobs.yml
  loop: "{{ wp_nodes }}"
