---
- name: Job Block
  block:
    - name: Launch
      awx.awx.job_launch:
        controller_host: "{{ vars.aap.controller_host }}"
        controller_oauthtoken: "{{ vars.aap.controller_oauthtoken }}"
        job_template: "{{ vars.aap.job_template }}"
        extra_vars:
          variable_host: "{{ item.metadata.name }}"
        wait: true
      register: launch_results
    - name: Report Job Run Success
      operator_sdk.util.k8s_status:
        api_version: "upgrade.example.com/v1alpha1"
        kind: Plan
        name: "{{ ansible_operator_meta.name }}"
        namespace: "{{ ansible_operator_meta.namespace }}"
        status:
          job:
            status: "completed"
            msg: "job_launch {{ launch_results.id }} was run successfully"
  rescue:
    - name: Report Job Run Failure
      operator_sdk.util.k8s_status:
        api_version: "upgrade.example.com/v1alpha1"
        kind: Plan
        name: "{{ ansible_operator_meta.name }}"
        namespace: "{{ ansible_operator_meta.namespace }}"
        status:
          job:
            status: "failed"
            msg: "{{ ansible_failed_result | community.general.json_query('msg') }}"

- name: Add Mutable Label
  kubernetes.core.k8s_json_patch:
    kind: Node
    api_version: "v1"
    name: "{{ item.metadata.name }}"
    patch:
      - op: add
        path: "/metadata/labels/upgrades.example.com~1mutable"
        value: ''

- name: Wait Until Node Version Matches Desired Version
  kubernetes.core.k8s_info:
    api_version: "v1"
    kind: Node
    name: "{{ item.metadata.name }}"
  register: actual_version
  until: desired_version[0] == actual_version.resources[0].metadata.labels['machineconfiguration.openshift.io/release-image-version']

- name: Remove Mutable Label
  kubernetes.core.k8s_json_patch:
    kind: Node
    api_version: "v1"
    name: "{{ item.metadata.name }}"
    patch:
      - op: remove
        path: "/metadata/labels/upgrades.example.com~1mutable"