---
- name: Gather Cluster Verion Info
  kubernetes.core.k8s_info:
    api_version: "config.openshift.io/v1"
    kind: ClusterVersion
    name: version
  register: version

- name: Set MCP Facts
  ansible.builtin.set_fact:
    desired_version: "{{ version | community.general.json_query(query) }}"
  vars:
    query: 'resources[*].spec.desiredUpdate.version'

- name: Gather Node Info
  kubernetes.core.k8s_info:
    api_version: "v1"
    kind: Node
  register: nodes

- name: Set Worker Node Version Facts
  ansible.builtin.set_fact:
    worker_node_version: "{{ nodes | community.general.json_query(query) }}"
  vars:
    query: >-
      resources[?(metadata.labels."node-role.kubernetes.io/worker"=='')].metadata.labels."machineconfiguration.openshift.io/release-image-version"

- name: Compare 'desired_version' to 'worker_node_version'
  ansible.builtin.set_fact:
    version_skew: "true"
  loop: "{{ worker_node_version }}"
  when: item is version(desired_version[0],'lt', version_type='semver')

- name: Report Updateability
  operator_sdk.util.k8s_status:
    api_version: "upgrade.example.com/v1alpha1"
    kind: Plan
    name: "{{ ansible_operator_meta.name }}"
    namespace: "{{ ansible_operator_meta.namespace }}"
    status:
      upgradeable: "{{ version_skew is defined }}"