---
- name: Gather Cluster Verion Info
  kubernetes.core.k8s_info:
    api_version: "config.openshift.io/v1"
    kind: ClusterVersion
    name: version
  register: version

- name: Set MCP Facts
  ansible.builtin.set_fact:
    desired_version: "{{ version | community.general.json_query(query) }}"
  vars:
    query: 'resources[*].spec.desiredUpdate.version'

- name: Gather Node Info
  kubernetes.core.k8s_info:
    api_version: "v1"
    kind: Node
  register: nodes

- name: Report Updateability
  operator_sdk.util.k8s_status:
    api_version: "upgrade.example.com/v1alpha1"
    kind: Plan
    name: "{{ ansible_operator_meta.name }}"
    namespace: "{{ ansible_operator_meta.namespace }}"
    status:
      desired_version: "{{ desired_version }}"
