---
- name: Gather Cluster Verion Info
  kubernetes.core.k8s_info:
    api_version: "config.openshift.io/v1"
    kind: ClusterVersion
    name: version
  register: version

- name: Get Cluster Version History
  ansible.builtin.set_fact:
    version_status: "{{ version | community.general.json_query(query) }}"
  vars:
    query: 'resources[*].status.history[]'

- name: Print return information from the previous task
  ansible.builtin.debug:
    msg: "{{ version_status }}"


- name: Set Version Status
  operator_sdk.util.k8s_status:
    api_version: "upgrade.example.com/v1alpha1"
    kind: Plan
    name: "{{ ansible_operator_meta.name }}"
    namespace: "{{ ansible_operator_meta.namespace }}"
    status:
      update_status: "{{ version_status | first }}"
