---
- name: Example Node Operations
  hosts: "{{ variable_host | default('localhost') }}"
  gather_facts: no

  tasks:
    # Print Vars
    - name: Print Vars
      ansible.builtin.debug:
        msg: "{{ vars }}"

    - name: Pause
      minutes: 5
